### ISSUE TITLE
New want: Improved web site security by default

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#36]
---
title: Improved web site security by default
date: 2020-03-05T18:35:46.474Z
submitter: PRIVATE
number: 5e6146823a8bd7017a7eb071
tags: []
---

Web site security is poorly understood and even more poorly handled (in general). Changing defaults would help a lot.

**Comment by aarongustafson** [comment]
Following up with the author to request more details.

**Comment by c1ue11** [comment]
Web site security:
While larger organizations have a CSP - content security policy, it would be nice to have a better set of defaults for the much more numerous organizations that do not.
In particular: lock down, by default, execution of scripts, images etc outside of owner and perhaps common 3rd parties like Google analytics.
It would also be good if there were some ways to see/monitor what javascripts are loaded, particularly by approved 3rd parties.
This in turn implies potential value in creating and maintaining a "white list" of known good 3rd parties.

**Comment by aarongustafson** [comment]
> In particular: lock down, by default, execution of scripts, images etc outside of owner and perhaps common 3rd parties like Google analytics.
> It would also be good if there were some ways to see/monitor what javascripts are loaded, particularly by approved 3rd parties.
> This in turn implies potential value in creating and maintaining a "white list" of known good 3rd parties.

How would this differ from the tracking prevention tools many browsers have already implemented?

**Comment by c1ue11** [comment]
browsers are used by the end consumer.
I'm talking about the web sites put up by companies - the places visited by consumers.
A web site can be compromised a number of ways for a number of reasons including:
1) software/browser extension putting up a window on a bank web site to capture PII. In other words, the normal bank web site is shown but an extra window is inserted asking for PII
2) Reading/modifying cookies - including ad fraud such as improper 3rd party reference
3) CSS is a language, you can even technically use it to brute force session cookies
All of these are possible because by default, execution of scripts/source/java/images on a web page is allowed.

**Comment by aarongustafson** [comment]
@c1ue11 This is a bit too broad as a single want. In order to have a focused and productive discussion about the security/privacy suggestions you’ve got here, could you resubmit them as individual wants?
