### ISSUE TITLE
New want: Have a CSS-only way to distinguish focus given to element via keyboard vs pointing device

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#43]
---
title: Have a CSS-only way to distinguish focus given to element via keyboard vs pointing device
date: 2020-04-04T17:59:52.029Z
submitter: PRIVATE
number: 5e88cb180972dc7f798d7c41
tags: []
---

Currently it's impossible to distinguish in CSS whether the focus was given to the element via keyboard vs via mouse/touch device.

To be able to do it, you need complex JavaScript tracking of focus.

This is problematic, because in general websites want to present focus outlines to elements focused via keyboard, and don't want them if focus comes from pointing devices.

Since it's difficult to do it properly, the websites typically take the "line of least resistance" and go for visually pleasing removal of focusing indicator for both scenarios, harming keyboard accessibility of the page.

Even if websites take the task of tracking focus via JavaScript, this is notoriously hard to do correctly, so it's still not a guarantee of success.

**Comment by jakub-g** [comment]
For info I'm the author of the issue. The problem is much larger than I described, and I don't really have a good problem description nor the solution.

**In general as a user, it's difficult to know where my focus is on the page, especially when scrolling.**

On Twitter, you have the situation I described: you see focus on keyboard interactions, not on mouse interactions, but even if not displayed it stays there. For example, after mouse-clicking a "like" button (which is really a div), it keeps the focus.

Then you press `spacebar` on keyboard, and instead of scrolling the page, it undoes the like (activates the "like" button again).

This is even more confusing when you scroll away (with mouse for example), so you don't see the focused like button anymore, and then press `spacebar`. The focus is out of viewport, but it still is there. When you press `spacebar`, you unlike the the thing you liked before, without knowing it (as it happens out of the viewport).

--

Apart from that, as a user, say I scroll down a long text article. My focus stays at the beginning of it, but it's hidden. Then I use `Tab` or `shift-arrow` to navigate or expand text selection, but since my focus is far out of the viewport, I get scrolled back to the top of the page.

*There are no means in the browsers to get the focus into the current viewport*. Neither does `F7` caret browsing work for that.

https://twitter.com/__jakub_g/status/1227912757401522176

**Comment by jakub-g** [comment]
FYI @simevidas @HugoGiraudel

**Comment by simevidas** [comment]
What are the different ways to focus an element via keyboard? Just the <kbd>Tab</kbd> key?

**Comment by jakub-g** [comment]
I'm mixing above the focus and caret position, sorry for that.

Regarding:
> What are the different ways to focus an element via keyboard? Just the Tab key?

In Firefox you can use `'` (quick search, links only) followed by `Esc`, to obtain _focus_ on the found text element. (Probably rather few people use this though).

In all browsers, you can also use `CTRL-F` followed by `Esc` to obtain _text selection_ on the found text element.

**Comment by simevidas** [comment]
That will set the [sequential focus navigation starting point](https://www.chromestatus.com/feature/5671747802103808), but the element will not be focused I think.

Test page: https://output.jsbin.com/vuhazuk/quiet

**Comment by captainbrosset** [comment]
It might be useful to elaborate here on the reasons for the following:

> Even if websites take the task of tracking focus via JavaScript, this is notoriously hard to do correctly, so it's still not a guarantee of success.

@jakub-g could you point to examples of where this is done (maybe something on stackoverflow, or other) and why it is hard?

**Comment by aarongustafson** [comment]
::bump:: @jakub-g 

Should we continue discussing or should I close out this issue?

**Comment by jakub-g** [comment]
Sorry for no response earlier.

I think my original problem is solved by `focus-visible` which BTW just landed in Chrome 86.
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

**Comment by aarongustafson** [comment]
Thanks @jakub-g! For what it’s worth, CSS4 also has media queries related to this: https://drafts.csswg.org/mediaqueries-4/#mf-interaction
