### ISSUE TITLE
I want easy access to common namespace URIs

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#74]
Every time I author SVGs using JavaScript—without a library—I end up having to look up the SVG namespace URI (and others) to make sure that the elements I create behave properly. It seems like an enormous oversight that I can’t access the “http://www.w3.org/2000/svg” URI (or other equivalent XML namespace URIs) from, say, a static property on the SVGElement constructor or something. Instead I have look it up, or (if I’m feeling clever) find some way to trick the parser into handing me a properly constructed SVG element, all so the browser can see the magic 26 letters that will cause my paths to display.

Here’s an example of what I could do if the browser has a set of predefined constants available to use:

```js
// if NS_SVG was a global constant defining the SVG namespace URI
var image = document.createElementNS( NS_SVG, 'image');
```

Here’s what that might look like if the namespace was defined on the element representation instead:

```js
const NS = SVGElement.NAMESPACE_URI;
var svg = document.createElementNS( NS, 'svg' );
```

Please, please, create a common way that I can access these and other namespace constants directly in my scripts. I don’t have to look up the exact integers that represent WebGL constants and we successfully simplified the HTML doctype… I have confidence that we can make this happen.

<hr>

https://webwewant.fyi/wants/5f7dc6381eb8b910287121e6/

**Comment by aarongustafson** [comment]
@thomaswilburn Are you thinking of this more in the context of an editor like VS Code or specifically in the browser?

**Comment by thomaswilburn** [comment]
Specifically in the browser.

**Comment by aarongustafson** [comment]
Can you walk me through a scenario? Are you authoring SVG in the browser?

**Comment by thomaswilburn** [comment]
Sure, so I do work with data visualization for my day job, and a lot of times SVG is a great way to make that happen. But I don't always want to use something like `d3-selection` (in fact, given a choice, I would prefer never to use `d3-selection`), especially since D3 is so modular these days that I can do my DOM manipulation in vanilla JS or a framework and just use D3 for the stuff that I don't want to hand-code, like force directed graphs.

However, if I'm building SVG dynamically, I often run into cases where the SVG tag doesn't exist at the start, or I'm needing to generate elements inside an existing element, and for those I need to create them with `document.createElementNS()`. At that point, I need the SVG namespace URI. I can look that up, sure. But it feels to me like I ought to be able to get to it somewhere automatically, since the browser knows full well what it is. I'd love to be able to do:

```js
var NS = SVGElement.NAMESPACE_URI;
var svg = document.createElementNS(NS, "svg");
var path = document.createElementNS(NS, "path");
```

Or something similar, rather than having magic strings in my code.

**Comment by aarongustafson** [comment]
This is really helpful @thomaswilburn, thank you.

When you are doing this work, are you typically doing the JS authoring in DevTools or something else?

**Comment by thomaswilburn** [comment]
Not typically, although that's another case where it's really useful to have it handy.

**Comment by aarongustafson** [comment]
I think I was looking at this incorrectly. For some reason I was thinking you were looking for autocompletion along the lines of IntelliSense (or similar).

If I’m following correctly now, you’re interested in, essentially, having elements carry their namespace URI along with them or in having some predefined constants for each of the commonly used namespaces (svg, xlink, etc.) kinda like how they get declared to variables in [this MDN documentation](https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course) example:

```js
var SVG_NS = 'http://www.w3.org/2000/svg';
var XLink_NS = 'http://www.w3.org/1999/xlink';
var image = document.createElementNS(SVG_NS, 'image');
image.setAttributeNS(null, 'width', '100');
image.setAttributeNS(null, 'height', '100');
image.setAttributeNS(XLink_NS, 'xlink:href', 'flower.png');
```

**Comment by thomaswilburn** [comment]
Exactly!

**Comment by aarongustafson** [comment]
Publishing now. Will move to discussion and clear out the unnecessary discussion. Let me know if the minor rewrite doesn’t capture everything you’re looking for.
